# Chunking Retrieval Debugger

Inspect why specific questions fail for different chunking strategies.
Ask a question, see the top-k chunks retrieved by each chunker, and compare.

In [11]:
import sys
from pathlib import Path

# Setup paths — works whether you run from experiments/chunking/ or project root
if Path.cwd().name == 'chunking':
    PROJECT_ROOT = Path.cwd().parent.parent
else:
    PROJECT_ROOT = Path.cwd()

sys.path.insert(0, str(PROJECT_ROOT))
sys.path.insert(0, str(PROJECT_ROOT / 'parsers'))

import numpy as np
import json
import pymupdf4llm

from experiments.chunking.chunkers import (
    get_all_chunkers, split_into_pages, split_into_elements,
    count_tokens, Chunk, ChunkType,
    PageLevelChunker, FixedSizeTokenChunker, RecursiveChunker,
    HeadingBasedChunker, TableAwareChunker, ElementTypeChunker,
    SemanticChunker, StructureAwareChunker,
)
from experiments.chunking.embedder import Embedder, cosine_similarity, BM25Index, hybrid_scores
from pymupdf_fast import parse_document as pymupdf_fast_parse

# Load QA pairs
with open(PROJECT_ROOT / 'experiments' / 'chunking' / 'qa_pairs.json') as f:
    qa_data = json.load(f)['documents']

embedder = Embedder()
print('Imports OK')
print(f'Project root: {PROJECT_ROOT}')
print(f'Available docs: {list(qa_data.keys())}')

Imports OK
Project root: /Users/sarath/work/doc-parser
Available docs: ['VAM-3852AO', 'hubspot-q4', 'hubspot-deck', '2023_report_40_pages', '10Q', 'kiski', 'report']

## 1. Load a document with both parsers

In [12]:
# ---- EDIT THIS ----
DOC = 'hubspot-q4'
# -------------------

pdf_path = PROJECT_ROOT / 'docs' / f'{DOC}.pdf'

# Parse with both approaches
md_fast = pymupdf_fast_parse(pdf_path)
md_4llm = pymupdf4llm.to_markdown(str(pdf_path), show_progress=False)

# Load questions
questions = qa_data[DOC]['questions']

print(f'Document: {DOC}')
print(f'pymupdf_fast:  {len(md_fast):>8} chars, {len(md_fast.splitlines()):>5} lines')
print(f'pymupdf4llm:   {len(md_4llm):>8} chars, {len(md_4llm.splitlines()):>5} lines')

# Count pipe-table lines
pipes_fast = sum(1 for l in md_fast.splitlines() if l.strip().startswith('|'))
pipes_4llm = sum(1 for l in md_4llm.splitlines() if l.strip().startswith('|'))
print(f'\nPipe-table lines: pymupdf_fast={pipes_fast}, pymupdf4llm={pipes_4llm}')

# Check key values
print(f'\n{"Keyword":<15} {"pymupdf_fast":<15} {"pymupdf4llm":<15}')
print('-' * 45)
for kw in [q['expected_keywords'][0] for q in questions]:
    in_fast = 'FOUND' if kw in md_fast else 'MISSING'
    in_4llm = 'FOUND' if kw in md_4llm else 'MISSING'
    print(f'{kw:<15} {in_fast:<15} {in_4llm:<15}')

Document: hubspot-q4
pymupdf_fast:     59043 chars,  2891 lines
pymupdf4llm:      44743 chars,   376 lines

Pipe-table lines: pymupdf_fast=261, pymupdf4llm=95

Keyword         pymupdf_fast    pymupdf4llm
---------------------------------------------
846.7           FOUND           FOUND
22.6%           FOUND           FOUND
288,706         FOUND           FOUND
3,854,151       FOUND           FOUND
709,045         FOUND           FOUND
884,945         FOUND           FOUND
3.69            FOUND           FOUND
829.0           FOUND           FOUND
1.04            FOUND           FOUND
1.0 billion     FOUND           FOUND

In [22]:
print(md_4llm)

**==> picture [75 x 21] intentionally omitted <==**

## **HubSpot Reports Strong Q4 and Full Year 2025 Results**

February 11, 2026

_Q4'25 revenue grew 20% on an as-reported basis and 18% in constant currency compared to Q4'24 Full year 2025 revenue grew 19% on an as-reported basis and 18% in constant currency compared to 2024_

CAMBRIDGE, Mass.--(BUSINESS WIRE)--Feb. 11, 2026-- HubSpot, Inc. (NYSE: HUBS), the customer platform for scaling companies, today announced financial results for the fourth quarter and full year ended December 31, 2025.

## **Financial Highlights:**

## **Revenue**

_Fourth Quarter 2025:_

- Total revenue was $846.7 million, up 20% on an as-reported basis and 18% in constant currency compared to Q4'24.

   - Subscription revenue was $829.0 million, up 21% on an as-reported basis compared to Q4'24.

   - Professional services and other revenue was $17.8 million, up 12% on an as-reported basis compared to Q4'24.

_Full Year 2025:_

- Total revenue was $3.13 billion, up 19% on an as-reported basis and 18% in constant currency compared to 2024.

   - Subscription revenue was $3.06 billion, up 19% on an as-reported basis compared to 2024.

   - Professional services and other revenue was $67.3 million, up 16% on an as-reported basis compared to 2024.

**Operating Income (Loss)**

_Fourth Quarter 2025:_

- GAAP operating margin was 5.7%, compared to (1.5%) in Q4'24.

- Non-GAAP operating margin was 22.6%, compared to 18.9% in Q4'24.

- GAAP operating income was $48.2 million, compared to operating loss of ($10.8) million in Q4'24.

- Non-GAAP operating income was $191.0 million, compared to $133.1 million in Q4'24.

_Full Year 2025:_

- GAAP operating margin was 0.2%, compared to (2.6%) in 2024.

- Non-GAAP operating margin was 18.6%, compared to 17.5% in 2024.

- GAAP operating income was $7.4 million, compared to operating loss of ($67.6) million in 2024.

Non-GAAP operating income was $581.9 million, compared to $460.2 million in 2024.

**Net Income** _Fourth Quarter 2025:_

- GAAP net income was $54.4 million, or $1.04 per basic and diluted share, compared to $4.9 million, or $0.10 per basic and $0.09 per diluted share in Q4'24.

- Non-GAAP net income was $162.5 million, or $3.10 per basic and $3.09 per diluted share, compared to $124.9 million, or $2.42 per basic and $2.32 per diluted share in Q4'24.

- Weighted average basic and diluted shares outstanding for GAAP net income per share was

52.5 million, compared to 51.7 million basic and 52.2 million diluted shares in Q4'24.

- Weighted average basic and diluted shares outstanding for non-GAAP net income per share was 52.5 million, compared to 51.7 million and 53.9 million, respectively in Q4'24.

## _Full Year 2025:_

- GAAP net income was $45.9 million, or $0.88 per basic and $0.86 per diluted share, compared to $4.6 million, or $0.09 per basic and diluted share in 2024.

- Non-GAAP net income was $516.0 million, or $9.84 per basic and $9.70 per diluted share, compared to $434.1 million, or $8.48 per basic and $8.12 per diluted share in 2024. Weighted average basic and diluted shares outstanding for GAAP net income per share was 52.5 million and 53.2 million, respectively, compared to 51.2 million basic and 51.8 million diluted shares in 2024.

- Weighted average basic and diluted shares outstanding for non-GAAP net income per share was 52.5 million and 53.2 million, respectively, compared to 51.2 million and 53.4 million, respectively in 2024.

## **Balance Sheet and Cash Flow**

- The company’s cash and cash equivalents, short-term, and long-term investments balance was $1.8 billion as of December 31, 2025.

- During the fourth quarter, the company generated $247.4 million of cash from operating cash flow, compared to $194.1 million during Q4'24.

- During the fourth quarter, the company generated $253.1 million of cash from non-GAAP operating cash flow and $209.4 million of non-GAAP free cash flow, compared to $198.6 million of cash from non-GAAP operating cash flow and $163.0 million of non-GAAP free cash flow during Q4'24.

- During 2025, the company generated $760.7 million of cash from operating cash flow, compared to $598.6 million during 2024.

- During 2025, the company generated $778.7 million of cash from non-GAAP operating cash flow and $594.9 million of non-GAAP free cash flow, compared to $615.6 million of cash from non-GAAP operating cash flow and $488.1 million of non-GAAP free cash flow during 2024.

## **Additional Recent Business Highlights**

- Grew Customers to 288,706 at December 31, 2025, up 16% from December 31, 2024. Average Subscription Revenue Per Customer was $11,683 during the fourth quarter of 2025, up 3% on an as-reported basis compared to the fourth quarter of 2024.

- Calculated billings were $971.4 million in the fourth quarter of 2025, up 27% on an as-reported basis and 20% in constant currency compared to Q4'24.

“2025 was a transformative year for HubSpot, defined by the momentum of our agentic customer platform and clear acceleration upmarket,” said Yamini Rangan, Chief Executive Officer at HubSpot. “AI adoption gathered pace, as Breeze Customer Agent and Breeze Prospecting Agent delivered real outcomes for customers. At the same time, our upmarket business saw strong momentum, as large companies turned to HubSpot to drive AI innovation, consolidate tech stacks, and reduce their total cost of ownership. Heading into 2026, we're cementing our position as the leading agentic customer platform for scaling companies, building on our strength upmarket, and leading the new era of marketing with products and a playbook that drive growth. We're entering the year with focus and urgency, and I'm confident we're positioned to drive durable growth in the years ahead.”

## **Share Repurchase Program**

On February 7, 2026, the company’s Board of Directors authorized a share repurchase program for the repurchase of shares of the company’s common stock, in an aggregate amount of up to $1.0 billion (the “2026 Share Repurchase Program”) over a period of up to 24 months. Repurchases under this program will be made in the open market, through privately negotiated transactions or other means, including pursuant to 10b5-1 plans, and in compliance with applicable securities laws and other requirements. The timing, manner, price, and amount of the 2026 Share Repurchase Program will be subject to the discretion of the Company’s management. The 2026 Share Repurchase Program does not obligate the Company to acquire a specified number of shares, and may be suspended, modified, or terminated at any time, without prior notice.

## **Business Outlook**

Based on information available as of February 11, 2026, HubSpot is issuing guidance for the first quarter and full year of 2026 as indicated below.

**First Quarter 2026:**

- Total revenue is expected to be in the range of $862.0 million to $863.0 million, up 21% year over year on an as-reported basis and 16% in constant currency.

- Non-GAAP operating income is expected to be in the range of $144.0 million to $145.0 million, representing a 17% operating profit margin.

- Non-GAAP net income per common share is expected to be in the range of $2.46 to $2.48. This assumes approximately 52.5 million weighted average diluted shares outstanding.

## **Full Year 2026:**

- Total revenue is expected to be in the range of $3.69 billion to $3.70 billion, up 18% year over year on an as-reported basis and 16% in constant currency.

- Non-GAAP operating income is expected to be in the range of $736.0 million to $740.0 million, representing a 20% operating profit margin.

- Non-GAAP net income per common share is expected to be in the range of $12.38 to $12.46. This assumes approximately 51.8 million weighted average diluted shares outstanding.

## **Use of Non-GAAP Financial Measures**

In our earnings press releases, conference calls, slide presentations, and webcasts, we may use or discuss non-GAAP financial measures, as defined by Regulation G. The GAAP financial measure most directly comparable to each non-GAAP financial measure used or discussed, and a reconciliation of the differences between each non-GAAP financial measure and the comparable GAAP financial measure, are included in this press release after the consolidated financial statements. Our earnings press releases containing such non-GAAP reconciliations can be found in the Investors section of our website ir.hubspot.com.

## **Conference Call Information**

HubSpot will host a conference call on Wednesday, February 11, 2026 at 4:30 p.m. Eastern Time (ET) to discuss the company’s fourth quarter and full year 2025 financial results and its business outlook. To register for this conference call, please use this dial in registration link or visit HubSpot's Investor Relations website at ir.hubspot.com. After registering, a confirmation email will be sent, including dial-in details and a unique code for entry. Participants who wish to register for the conference call webcast please use this link.

An archived webcast of this conference call will also be available on HubSpot's Investor Relations website at ir.hubspot.com.

The company has used, and intends to continue to use, the investor relations portion of its website as a means of disclosing material non-public information and for complying with disclosure obligations under Regulation FD.

## **About HubSpot**

HubSpot is the agentic customer platform that helps businesses connect and grow better. HubSpot delivers seamless connection for customer-facing teams with a unified platform that includes AI-powered engagement hubs, a Smart CRM, and a connected ecosystem with over 2,000 App Marketplace integrations, a community network, and educational content. Learn more at www.hubspot.com.

## **Cautionary Language Concerning Forward-Looking Statements**

This press release includes certain “forward-looking statements” within the meaning of the Private Securities Litigation Reform Act of 1995, including statements regarding management’s expectations of future financial and operational performance and operational expenditures, expected growth, foreign currency movement, and business outlook, including our financial guidance for the first fiscal quarter of and full year 2026 and our long-term financial framework; statements regarding our share repurchase program; statements regarding our positioning for future growth and market leadership; statements regarding the strength of our agentic customer platform; statements regarding the growth or maintenance of our upmarket business; statements regarding the economic environment; and statements regarding expected market trends, future priorities and related investments, and market opportunities. These forward-looking statements include, but are not limited to, plans, objectives, expectations and intentions and other statements contained in this press release that are not historical facts and statements identified by words such as “expects,” “anticipates,” “intends,” “plans,” “believes,” “seeks,” “estimates” or words of similar meaning. These forward-looking statements reflect our current views about our plans, intentions, expectations, strategies and prospects, which are based on the information currently available to us and on assumptions we have made. Although we believe that our plans, intentions, expectations, strategies and prospects as reflected in or suggested by those forward-looking statements are reasonable, we can give no assurance that the plans, intentions, expectations or strategies will be attained or achieved. Furthermore, actual results may differ materially from those described in the forward-looking statements and will be affected by a variety of risks and factors that are beyond our control including, without limitation, risks associated with our history of losses; our ability to retain existing customers and add new customers; the continued growth of the market for a customer platform; our ability to develop new products and technologies and differentiate our platform from competing products and technologies, including artificial intelligence and machine learning technologies; our ability to manage our growth effectively over the long-term to maintain our high level of service; our ability to maintain and expand relationships with our solutions partners; the price volatility of our common stock; the impact of geopolitical conflicts, inflation, foreign currency movement, and macroeconomic instability on our business, the broader economy, our workforce and operations, the markets in which we and our partners and customers operate, and our ability to forecast our future financial performance; regulatory and legislative developments on the use of artificial intelligence and machine learning; and other risks set forth under the caption “Risk Factors” in our SEC filings. We assume no obligation to update any forward-looking statements contained in this document as a result of new information, future events or otherwise.

## **Consolidated Balance Sheets**

(in thousands)

**December 31, December 31, 2025 2024**

**Assets**

|Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development costs, net<br>Right-of-use assets<br>Deferred commission expense, net of current portion<br>Other assets<br>Intangible assets, net<br>Goodwill<br> <br>**Total assets**<br> <br>**Liabilities and stockholders’ equity**<br>Current liabilities:<br>Accounts payable<br>Accrued compensation costs<br>Accrued commissions<br>Accrued expenses and other current liabilities<br>Operating lease liabilities<br>Convertible senior notes<br>Deferred revenue<br> <br>Total current liabilities<br>Operating lease liabilities, net of current portion<br>Deferred revenue, net of current portion<br>Other long-term liabilities<br> <br>Total liabilities<br>Stockholders’ equity:<br>Common stock<br>Treasury stock<br>Additional paid-in capital<br>Accumulated other comprehensive income (loss)<br>Accumulated deficit<br> <br>Total stockholders’ equity<br> <br>**Total liabilities and stockholders’ equity**<br>|$ 882,242<br>821,552<br>419,146<br>226,184<br>100,611  <br>2,449,735<br>136,662<br>141,869<br>213,794<br>200,821<br>218,991<br>165,602<br>35,225<br>291,452  <br>3,854,151  <br>24,764<br>99,195<br>132,003<br>166,861<br>39,703<br>—<br>1,004,945  <br>1,467,471<br>222,602<br>8,495<br>89,339  <br>1,787,907<br>53<br>2<br>2,814,843<br>5,244<br>(753,898)  <br>2,066,244  <br>$ 3,854,151|$ 512,667<br> <br>1,556,828<br> <br>334,829<br> <br>148,693<br> <br>80,586|
|---|---|---|
|||<br>2,633,603<br> <br>154,212<br> <br>114,165<br> <br>154,484<br> <br>216,230<br> <br>160,814<br> <br>115,254<br> <br>37,563<br> <br>209,508|
|||<br>3,795,833|
|||<br>3,649<br> <br>67,442<br> <br>102,043<br> <br>125,135<br> <br>32,693<br> <br>458,184<br> <br>784,253|
|||<br>1,573,399<br> <br>254,539<br> <br>3,969<br> <br>55,640|
|||<br>1,887,547<br> <br>52<br> <br>—<br> <br>2,713,697<br> <br>(5,654)<br> <br>(799,809)|
|||<br>1,908,286|
|||$ 3,795,833|



## **Consolidated Statements of Operations**

(in thousands, except per share data)

|Revenues:<br>Subscription<br>Professional services and other<br>Total revenue<br>Cost of revenues:<br>Subscription<br>Professional services and other<br>Total cost of revenues<br>Gross profit<br>Operating expenses:<br>Research and development<br>Sales and marketing<br>General and administrative<br>Restructuring<br>Total operating expenses<br>Income (loss) from operations<br>Other income (expense)<br>Interest income<br>Interest expense|**Three Months Ended December 31,** <br>**2025**<br> <br>**2024**<br> <br>$ 828,980  $ 687,316<br>17,766  <br>15,856 <br>846,746  <br>703,172 <br>121,411<br>89,505<br>16,290  <br>13,867 <br>137,701  <br>103,372 <br>709,045  <br>599,800 <br>220,794<br>213,711<br>357,531<br>314,864<br>81,668<br>80,931<br>814  <br>1,143 <br>660,807  <br>610,649 <br>48,238  <br>(10,849) <br>13,112<br>21,829<br>—<br>(949)|**Year Ended December 31,**|**Year Ended December 31,**|
|---|---|---|---|
||**2025**<br> <br>$ 828,980<br>17,766  <br>846,746  <br>121,411<br>16,290  <br>137,701  <br>709,045  <br>220,794<br>357,531<br>81,668<br>814  <br>660,807  <br>48,238  <br>13,112<br>—|<br>**2025**<br>|<br>**2024**|
|||$ 3,063,917<br> <br>67,349 <br> <br>3,131,266 <br> <br>445,336<br> <br>63,151 <br> <br>508,487 <br> <br>2,622,779 <br> <br>905,943<br> <br>1,379,376<br> <br>326,045<br> <br>4,036 <br> <br>2,615,400 <br>  <br>7,379 <br> <br>66,218<br> <br>(876)|$ 2,569,546<br> <br>57,997|
||||<br>2,627,543|
||||<br>336,878<br> <br>56,387|
||||<br>393,265|
||||<br>2,234,278|
||||<br>778,714<br> <br>1,218,844<br> <br>300,332<br> <br>3,990|
||||<br>2,301,880|
||||<br>(67,602)|
||||<br>82,706<br> <br>(3,721)|



|Other income (expense)<br>Total other income<br>Income before income tax expense<br>Income tax expense<br>Net income<br>Net income per share, basic<br>Net income per share, diluted<br>Weighted average common shares used in computing basic net<br>income per share:<br>Weighted average common shares used in computing diluted net<br>income per share|303  <br>13,415  <br>61,653<br>(7,227)  <br>54,426 <br>$ 1.04<br>$ 1.04<br>52,457<br>52,547|<br>2,913  <br> <br>23,793  <br> <br>12,944<br> <br>(8,009)  <br> <br>4,935 <br>$ 0.10<br>$ 0.09<br> <br>51,657<br> <br>52,242|<br>(3,258)  <br> <br>62,084  <br> <br>69,463<br> <br>(23,552)  <br> <br>45,911  <br>$ 0.88<br>$ 0.86<br> <br>52,455<br> <br>53,194|<br>17,294|
|---|---|---|---|---|
|||||<br>96,279|
|||||<br>28,677<br> <br>(24,049)|
|||||<br>4,628|
|||||$ 0.09<br>$ 0.09<br> <br>51,178<br> <br>51,819|



## **Consolidated Statements of Cash Flows**

(in thousands)


In [24]:
import pandas as pd

TOP_K = 5
RETRIEVAL = 'hybrid'  # 'dense', 'bm25', or 'hybrid'

def get_hit(data, q_emb, q, top_k, retrieval):
    dense_scores = cosine_similarity(q_emb, data['embeddings'])
    bm25_scores = data['bm25'].score(q['question'])
    if retrieval == 'dense': scores = dense_scores
    elif retrieval == 'bm25': scores = bm25_scores
    else: scores = hybrid_scores(dense_scores, bm25_scores)
    top_idx = np.argsort(scores)[::-1][:top_k]
    top_text = ' '.join(data['texts'][i] for i in top_idx)
    return any(kw.lower() in top_text.lower() for kw in q['expected_keywords'])

names = list(chunker_configs.keys())

# Collect results
rows = []
for q in questions:
    q_emb = embedder.embed_query(q['question'])
    for n in names:
        fh = get_hit(cd_fast[n], q_emb, q, TOP_K, RETRIEVAL)
        lh = get_hit(cd_4llm[n], q_emb, q, TOP_K, RETRIEVAL)
        rows.append({
            'question_id': q['id'],
            'question': q['question'],
            'expected_keywords': ', '.join(q['expected_keywords']),
            'chunker': n,
            'pymupdf_fast': 'HIT' if fh else 'MISS',
            'pymupdf4llm': 'HIT' if lh else 'MISS',
            'changed': '' if fh == lh else ('improved' if lh else 'regressed'),
        })

df = pd.DataFrame(rows)

# Save to CSV
out_path = PROJECT_ROOT / 'experiments' / 'chunking' / 'results' / f'debug_{DOC}.csv'
df.to_csv(out_path, index=False)
print(f'Saved to {out_path}')

# Also make a pivot view: questions as rows, chunkers as columns, parser as sub-columns
for parser_col, label in [('pymupdf_fast', 'pymupdf_fast'), ('pymupdf4llm', 'pymupdf4llm')]:
    pivot = df.pivot(index=['question_id', 'question'], columns='chunker', values=parser_col)
    pivot_path = PROJECT_ROOT / 'experiments' / 'chunking' / 'results' / f'debug_{DOC}_{label}_pivot.csv'
    pivot.to_csv(pivot_path)
    print(f'Saved pivot to {pivot_path}')

# Show the differences
diffs = df[df['changed'] != '']
if len(diffs) > 0:
    print(f'\n{len(diffs)} differences found:')
    display(diffs[['question_id', 'question', 'chunker', 'pymupdf_fast', 'pymupdf4llm', 'changed']])
else:
    print('\nNo differences — both parsers produce identical results')

# Show summary
print(f'\nSummary (top-{TOP_K}, {RETRIEVAL}):')
summary = df.groupby('chunker').agg(
    fast_hits=('pymupdf_fast', lambda x: (x == 'HIT').sum()),
    llm_hits=('pymupdf4llm', lambda x: (x == 'HIT').sum()),
).assign(
    total=len(questions),
    fast_pct=lambda x: (x.fast_hits / len(questions) * 100).round(0).astype(int),
    llm_pct=lambda x: (x.llm_hits / len(questions) * 100).round(0).astype(int),
)
display(summary)

Saved to /Users/sarath/work/doc-parser/experiments/chunking/results/debug_hubspot-q4.csv
Saved pivot to /Users/sarath/work/doc-parser/experiments/chunking/results/debug_hubspot-q4_pymupdf_fast_pivot.csv
Saved pivot to /Users/sarath/work/doc-parser/experiments/chunking/results/debug_hubspot-q4_pymupdf4llm_pivot.csv

4 differences found:

,question_id,question,chunker,pymupdf_fast,pymupdf4llm,changed
18,hub_04,What was HubSpot's total assets as of December...,page_level,MISS,HIT,improved
21,hub_04,What was HubSpot's total assets as of December...,structure_aware,HIT,MISS,regressed
22,hub_04,What was HubSpot's total assets as of December...,table_aware,HIT,MISS,regressed
24,hub_05,What was HubSpot's gross profit in Q4 2025?,page_level,MISS,HIT,improved

Summary (top-5, hybrid):

                   fast_hits  llm_hits  total  fast_pct  llm_pct
chunker
element_type               8         8     10        80       80
fixed_512_overlap          8         8     10        80       80
heading_based              8         8     10        80       80
page_level                 8        10     10        80      100
structure_aware            9         8     10        90       80
table_aware                9         8     10        90       80

In [13]:
# Find and display the first pipe-table block from pymupdf4llm
lines = md_4llm.split('\n')
in_table = False
table_start = None

for i, line in enumerate(lines):
    if line.strip().startswith('|') and not in_table:
        table_start = i
        in_table = True
    elif not line.strip().startswith('|') and in_table:
        print(f'First table: lines {table_start}-{i} ({i - table_start} lines)')
        print()
        for j in range(table_start, min(i, table_start + 20)):
            print(lines[j][:150])
        if i - table_start > 20:
            print(f'... ({i - table_start} lines total)')
        break

First table: lines 144-153 (9 lines)

|Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses
|---|---|---|
|||<br>2,633,603<br> <br>154,212<br> <br>114,165<br> <br>154,484<br> <br>216,230<br> <br>160,814<br> <br>115,254<br> <br>37,563<br> <br>209,508|
|||<br>3,795,833|
|||<br>3,649<br> <br>67,442<br> <br>102,043<br> <br>125,135<br> <br>32,693<br> <br>458,184<br> <br>784,253|
|||<br>1,573,399<br> <br>254,539<br> <br>3,969<br> <br>55,640|
|||<br>1,887,547<br> <br>52<br> <br>—<br> <br>2,713,697<br> <br>(5,654)<br> <br>(799,809)|
|||<br>1,908,286|
|||$ 3,795,833|

## 3. Chunk both outputs and compare

In [14]:
# Chunkers to compare
chunker_configs = {
    'page_level': PageLevelChunker(),
    'fixed_512_overlap': FixedSizeTokenChunker(chunk_size=512, overlap=102),
    'element_type': ElementTypeChunker(),
    'structure_aware': StructureAwareChunker(),
    'table_aware': TableAwareChunker(),
    'heading_based': HeadingBasedChunker(),
}

def build_chunker_data(markdown, label):
    data = {}
    for name, chunker in chunker_configs.items():
        chunks = chunker.chunk(markdown)
        texts = [c.text for c in chunks]
        embeddings = embedder.embed_texts(texts)
        bm25 = BM25Index(texts)
        table_count = sum(1 for c in chunks if c.metadata.get('chunk_type') == ChunkType.TABLE)
        data[name] = {'chunks': chunks, 'texts': texts, 'embeddings': embeddings, 'bm25': bm25}
        print(f'  {name}: {len(chunks)} chunks (tables: {table_count}), avg {np.mean([count_tokens(t) for t in texts]):.0f} tok')
    return data

print('pymupdf_fast:')
cd_fast = build_chunker_data(md_fast, 'fast')
print()
print('pymupdf4llm:')
cd_4llm = build_chunker_data(md_4llm, '4llm')

pymupdf_fast:
  page_level: 10 chunks (tables: 0), avg 1832 tok
  fixed_512_overlap: 49 chunks (tables: 0), avg 434 tok
  element_type: 372 chunks (tables: 181), avg 49 tok
  structure_aware: 379 chunks (tables: 181), avg 51 tok
  table_aware: 390 chunks (tables: 181), avg 47 tok
  heading_based: 27 chunks (tables: 8), avg 677 tok

pymupdf4llm:
  page_level: 1 chunks (tables: 0), avg 12885 tok
  fixed_512_overlap: 31 chunks (tables: 0), avg 468 tok
  element_type: 28 chunks (tables: 15), avg 459 tok
  structure_aware: 46 chunks (tables: 15), avg 284 tok
  table_aware: 38 chunks (tables: 15), avg 337 tok
  heading_based: 31 chunks (tables: 8), avg 415 tok

## 4. Side-by-side HIT/MISS matrix

In [23]:
TOP_K = 5
RETRIEVAL = 'hybrid'  # 'dense', 'bm25', or 'hybrid'

def get_hit(data, q_emb, q, top_k, retrieval):
    dense_scores = cosine_similarity(q_emb, data['embeddings'])
    bm25_scores = data['bm25'].score(q['question'])
    if retrieval == 'dense': scores = dense_scores
    elif retrieval == 'bm25': scores = bm25_scores
    else: scores = hybrid_scores(dense_scores, bm25_scores)
    top_idx = np.argsort(scores)[::-1][:top_k]
    top_text = ' '.join(data['texts'][i] for i in top_idx)
    return any(kw.lower() in top_text.lower() for kw in q['expected_keywords'])

names = list(chunker_configs.keys())
header = f"{'Q_ID':<10} {'Question':<40}"
for n in names:
    header += f" fast_{n[:8]:>10}  4llm_{n[:8]:>10}"
print(header)
print('-' * len(header))

# Track totals
fast_hits = {n: 0 for n in names}
llm_hits = {n: 0 for n in names}

for q in questions:
    q_emb = embedder.embed_query(q['question'])
    row = f"{q['id']:<10} {q['question'][:38]:<40}"
    for n in names:
        fh = get_hit(cd_fast[n], q_emb, q, TOP_K, RETRIEVAL)
        lh = get_hit(cd_4llm[n], q_emb, q, TOP_K, RETRIEVAL)
        fast_hits[n] += fh
        llm_hits[n] += lh
        fs = '  HIT' if fh else ' MISS'
        ls = '  HIT' if lh else ' MISS'
        row += f' {fs:>10}  {ls:>10}'
    print(row)

# Totals
print('-' * len(header))
total_row = f"{'TOTAL':<10} {'':40}"
for n in names:
    total_row += f" {fast_hits[n]:>10}  {llm_hits[n]:>10}"
print(total_row)

Q_ID       Question                                 fast_  page_lev  4llm_  page_lev fast_  fixed_51  4llm_  fixed_51 fast_  element_  4llm_  element_ fast_  structur  4llm_  structur fast_  table_aw  4llm_  table_aw fast_  heading_  4llm_  heading_
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
hub_01     What was HubSpot's total revenue in Q4          HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT
hub_02     What was HubSpot's non-GAAP operating           HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT
hub_03     How many customers did HubSpot have as          HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT
hub_04     What was HubSpot's total assets as of          MISS         HIT       MISS        MISS       MISS        MISS        HIT        MISS        HIT        MISS       MISS        MISS
hub_05     What was HubSpot's gross profit in Q4          MISS         HIT       MISS        MISS       MISS        MISS       MISS        MISS       MISS        MISS       MISS        MISS
hub_06     What was the cash and cash equivalents          HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT
hub_07     What is the expected total revenue for          HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT
hub_08     What was HubSpot's subscription revenu          HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT
hub_09     What was HubSpot's net income per dilu          HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT
hub_10     What was the share repurchase program           HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT        HIT         HIT
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
TOTAL                                                        8          10          8           8          8           8          9           8          9           8          8           8

## 5. Deep-dive: inspect a specific question

In [16]:
# ---- EDIT THIS ----
Q_ID = 'hub_04'
CHUNKER = 'table_aware'
# -------------------

q = next(q for q in questions if q['id'] == Q_ID)

for label, cd in [('pymupdf_fast', cd_fast), ('pymupdf4llm', cd_4llm)]:
    data = cd[CHUNKER]
    chunks = data['chunks']
    texts = data['texts']

    print(f"\n{'='*70}")
    print(f"{label} + {CHUNKER} ({len(chunks)} chunks)")
    print(f"Question: {q['question']}")
    print(f"Expected: {q['expected_keywords']}")
    print(f"{'='*70}")

    # Find answer chunks
    answer_chunks = [i for i, t in enumerate(texts)
                     if any(kw.lower() in t.lower() for kw in q['expected_keywords'])]

    if not answer_chunks:
        print('!! ANSWER NOT IN ANY CHUNK')
        continue

    print(f'Answer found in chunk(s): {answer_chunks}')
    for i in answer_chunks:
        page = chunks[i].metadata.get('page_num', '?')
        ctype = chunks[i].metadata.get('chunk_type', '?')
        tok = count_tokens(texts[i])
        print(f"\n  Chunk {i} [page {page}, {ctype}, {tok} tok]:")
        print(f"  {texts[i][:400]}...")

    # Rankings
    q_emb = embedder.embed_query(q['question'])
    dense_scores = cosine_similarity(q_emb, data['embeddings'])
    bm25_scores = data['bm25'].score(q['question'])
    hyb = hybrid_scores(dense_scores, bm25_scores)

    dense_ranks = np.argsort(np.argsort(-dense_scores))
    bm25_ranks = np.argsort(np.argsort(-bm25_scores))
    hybrid_ranks = np.argsort(np.argsort(-hyb))

    print(f"\n  {'Chunk':<8} {'Dense':<10} {'BM25':<10} {'Hybrid':<10}")
    for i in answer_chunks:
        print(f"  {i:<8} #{dense_ranks[i]+1:<9} #{bm25_ranks[i]+1:<9} #{hybrid_ranks[i]+1:<9}")

======================================================================
pymupdf_fast + table_aware (390 chunks)
Question: What was HubSpot's total assets as of December 31, 2025?
Expected: ['3,854,151']
======================================================================
Answer found in chunk(s): [8]

  Chunk 8 [page 4, ChunkType.TEXT, 512 tok]:
  Current assets:



Cash and cash equivalents
 $
882,242  $
512,667
Short-term investments

821,552
1,556,828
Accounts receivable

419,146
334,829
Deferred commission expense

226,184
148,693
Prepaid expenses and other current assets

100,611
80,586
Total current assets

2,449,735
2,633,603
Long-term investments

136,662
154,212
Property and equipment, net...

  Chunk    Dense      BM25       Hybrid
  8        #13        #5         #4

======================================================================
pymupdf4llm + table_aware (38 chunks)
Question: What was HubSpot's total assets as of December 31, 2025?
Expected: ['3,854,151']
======================================================================
Answer found in chunk(s): [7]

  Chunk 7 [page 1, ChunkType.TABLE, 764 tok]:
  |Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development costs, net<br>Right-of-use assets<br>Deferred commission expense, net of current portion<br>Other asset...

  Chunk    Dense      BM25       Hybrid
  7        #9         #31        #19

## 6. Compare chunk boundaries for a keyword

In [18]:
# ---- EDIT THIS ----
KEYWORD = '3,854,151'
CHUNKER = 'table_aware'
# -------------------

for label, cd in [('pymupdf_fast', cd_fast), ('pymupdf4llm', cd_4llm)]:
    data = cd[CHUNKER]
    print(f"\n{'='*70}")
    print(f"{label} + {CHUNKER} — {len(data['chunks'])} chunks")
    print(f"{'='*70}")
    found = False
    for i, (chunk, text) in enumerate(zip(data['chunks'], data['texts'])):
        if KEYWORD.lower() in text.lower():
            found = True
            page = chunk.metadata.get('page_num', '?')
            ctype = chunk.metadata.get('chunk_type', '?')
            tok = count_tokens(text)
            pos = text.lower().find(KEYWORD.lower())
            start = max(0, pos - 100)
            end = min(len(text), pos + len(KEYWORD) + 100)
            # context = text[start:end].replace('\n', ' ')
            context = text.replace('\n', ' ')
            print(f"\n  Chunk {i} [page {page}, {ctype}, {tok} tok]")
            print(f"  ...{context}...")
    if not found:
        print(f"  '{KEYWORD}' NOT FOUND in any chunk")

======================================================================
pymupdf_fast + table_aware — 390 chunks
======================================================================

  Chunk 8 [page 4, ChunkType.TEXT, 512 tok]
  ...Current assets:          Cash and cash equivalents  $ 882,242  $ 512,667  Short-term investments    821,552    1,556,828  Accounts receivable    419,146    334,829  Deferred commission expense    226,184    148,693  Prepaid expenses and other current assets    100,611    80,586  Total current assets    2,449,735    2,633,603  Long-term investments    136,662    154,212  Property and equipment, net    141,869    114,165  Capitalized software development costs, net    213,794    154,484  Right-of-use assets    200,821    216,230  Deferred commission expense, net of current portion    218,991    160,814  Other assets    165,602    115,254  Intangible assets, net    35,225    37,563  Goodwill    291,452    209,508  Total assets    3,854,151    3,795,833  Liabilities and stockholders’ equity          Current liabilities:          Accounts payable    24,764    3,649  Accrued compensation costs    99,195    67,442  Accrued commissions    132,003    102,043  Accrued expenses and other current liabilities    166,861    125,135  Operating lease liabilities    39,703    32,693  Convertible senior notes   —    458,184  Deferred revenue    1,004,945    784,253  Total current liabilities    1,467,471    1,573,399  Operating lease liabilities, net of current portion    222,602    254,539  Deferred revenue, net of current portion    8,495    3,969  Other long-term liabilities    89,339    55,640  Total liabilities    1,787,907    1,887,547  Stockholders’ equity:          Common stock    53    52  Treasury stock    2    —  Additional paid-in capital    2,814,843    2,713,697  Accumulated other comprehensive income (loss)    5,244    (5,654) Accumulated deficit    (753,898)    (799,809) Total stockholders’ equity    2,066,244    1,908,286  Total liabilities and stockholders’ equity  $ 3,854,151  $ 3,795,833 ...

======================================================================
pymupdf4llm + table_aware — 38 chunks
======================================================================

  Chunk 7 [page 1, ChunkType.TABLE, 764 tok]
  ...|Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development costs, net<br>Right-of-use assets<br>Deferred commission expense, net of current portion<br>Other assets<br>Intangible assets, net<br>Goodwill<br> <br>**Total assets**<br> <br>**Liabilities and stockholders’ equity**<br>Current liabilities:<br>Accounts payable<br>Accrued compensation costs<br>Accrued commissions<br>Accrued expenses and other current liabilities<br>Operating lease liabilities<br>Convertible senior notes<br>Deferred revenue<br> <br>Total current liabilities<br>Operating lease liabilities, net of current portion<br>Deferred revenue, net of current portion<br>Other long-term liabilities<br> <br>Total liabilities<br>Stockholders’ equity:<br>Common stock<br>Treasury stock<br>Additional paid-in capital<br>Accumulated other comprehensive income (loss)<br>Accumulated deficit<br> <br>Total stockholders’ equity<br> <br>**Total liabilities and stockholders’ equity**<br>|$ 882,242<br>821,552<br>419,146<br>226,184<br>100,611  <br>2,449,735<br>136,662<br>141,869<br>213,794<br>200,821<br>218,991<br>165,602<br>35,225<br>291,452  <br>3,854,151  <br>24,764<br>99,195<br>132,003<br>166,861<br>39,703<br>—<br>1,004,945  <br>1,467,471<br>222,602<br>8,495<br>89,339  <br>1,787,907<br>53<br>2<br>2,814,843<br>5,244<br>(753,898)  <br>2,066,244  <br>$ 3,854,151|$ 512,667<br> <br>1,556,828<br> <br>334,829<br> <br>148,693<br> <br>80,586| |---|---|---| |||<br>2,633,603<br> <br>154,212<br> <br>114,165<br> <br>154,484<br> <br>216,230<br> <br>160,814<br> <br>115,254<br> <br>37,563<br> <br>209,508| |||<br>3,795,833| |||<br>3,649<br> <br>67,442<br> <br>102,043<br> <br>125,135<br> <br>32,693<br> <br>458,184<br> <br>784,253| |||<br>1,573,399<br> <br>254,539<br> <br>3,969<br> <br>55,640| |||<br>1,887,547<br> <br>52<br> <br>—<br> <br>2,713,697<br> <br>(5,654)<br> <br>(799,809)| |||<br>1,908,286| |||$ 3,795,833|...

## 7. Ask a custom question

In [17]:
# ---- EDIT THIS ----
QUESTION = "What was HubSpot's total assets as of December 31, 2025?"
EXPECTED = ['3,854,151']
TOP_K = 5
RETRIEVAL = 'hybrid'
USE_4LLM = True  # False = pymupdf_fast, True = pymupdf4llm
# -------------------

cd = cd_4llm if USE_4LLM else cd_fast
label = 'pymupdf4llm' if USE_4LLM else 'pymupdf_fast'
q_emb = embedder.embed_query(QUESTION)

for name, data in cd.items():
    chunks = data['chunks']
    texts = data['texts']
    dense_scores = cosine_similarity(q_emb, data['embeddings'])
    bm25_scores = data['bm25'].score(QUESTION)
    if RETRIEVAL == 'dense': scores = dense_scores
    elif RETRIEVAL == 'bm25': scores = bm25_scores
    else: scores = hybrid_scores(dense_scores, bm25_scores)

    top_idx = np.argsort(scores)[::-1][:TOP_K]
    top_text = ' '.join(texts[i] for i in top_idx)
    hit = any(kw.lower() in top_text.lower() for kw in EXPECTED)

    print(f"\n{'='*80}")
    print(f"{label} + {name} — {'HIT' if hit else 'MISS'} (top-{TOP_K}, {RETRIEVAL})")
    print(f"{'='*80}")

    for rank, idx in enumerate(top_idx):
        page = chunks[idx].metadata.get('page_num', '?')
        ctype = chunks[idx].metadata.get('chunk_type', '?')
        tok = count_tokens(texts[idx])
        has_answer = any(kw.lower() in texts[idx].lower() for kw in EXPECTED)
        marker = ' << ANSWER' if has_answer else ''
        preview = texts[idx][:200].replace('\n', ' ')
        print(f"\n  #{rank+1} [page {page}, {ctype}, {tok} tok] dense={dense_scores[idx]:.3f} bm25={bm25_scores[idx]:.1f}{marker}")
        print(f"  {preview}...")

================================================================================
pymupdf4llm + page_level — HIT (top-5, hybrid)
================================================================================

  #1 [page 1, ChunkType.MIXED, 12885 tok] dense=0.431 bm25=-4.8 << ANSWER
  **==> picture [75 x 21] intentionally omitted <==**  ## **HubSpot Reports Strong Q4 and Full Year 2025 Results**   February 11, 2026   _Q4'25 revenue grew 20% on an as-reported basis and 18% in consta...

================================================================================
pymupdf4llm + fixed_512_overlap — MISS (top-5, hybrid)
================================================================================

  #1 [page 1, ChunkType.MIXED, 507 tok] dense=0.595 bm25=6.4
  **==> picture [75 x 21] intentionally omitted <==** ## **HubSpot Reports Strong Q4 and Full Year 2025 Results**  February 11, 2026  _Q4'25 revenue grew 20% on an as-reported basis and 18% in constant ...

  #2 [page 1, ChunkType.MIXED, 485 tok] dense=0.600 bm25=5.5
  ## **Additional Recent Business Highlights**  - Grew Customers to 288,706 at December 31, 2025, up 16% from December 31, 2024. Average Subscription Revenue Per Customer was $11,683 during the fourth q...

  #3 [page 1, ChunkType.MIXED, 348 tok] dense=0.593 bm25=4.1
  ||||||$ 548,237<br>$ 10.45<br>$ 10.31| > **(1)** Non-GAAP net income was $95.9 million, $117.3 million, $140.3 million, and $162.5 million for the three months ended March 31, 2025, June 30, 2025, Sep...

  #4 [page 1, ChunkType.MIXED, 506 tok] dense=0.489 bm25=6.0
  - A. Stock-based compensation is a non-cash expense accounted for in accordance with FASB ASC Topic 718. We believe that the exclusion of stock-based compensation expense allows for financial results ...

  #5 [page 1, ChunkType.MIXED, 495 tok] dense=0.572 bm25=3.8
  The timing, manner, price, and amount of the 2026 Share Repurchase Program will be subject to the discretion of the Company’s management. The 2026 Share Repurchase Program does not obligate the Compan...

================================================================================
pymupdf4llm + element_type — MISS (top-5, hybrid)
================================================================================

  #1 [page 1, ChunkType.CHART_DESCRIPTION, 3062 tok] dense=0.638 bm25=10.4
  **==> picture [75 x 21] intentionally omitted <==**  ## **HubSpot Reports Strong Q4 and Full Year 2025 Results**   February 11, 2026   _Q4'25 revenue grew 20% on an as-reported basis and 18% in consta...

  #2 [page 1, ChunkType.CHART_DESCRIPTION, 2038 tok] dense=0.469 bm25=7.7
  HubSpot’s estimates of stock-based compensation, amortization of acquired intangible assets, interest expense for amortization of one-time upfront debt issuance costs, restructuring charges, and incom...

  #3 [page 1, ChunkType.TEXT, 331 tok] dense=0.559 bm25=6.8
  > **(1)** Non-GAAP net income was $95.9 million, $117.3 million, $140.3 million, and $162.5 million for the three months ended March 31, 2025, June 30, 2025, September 30, 2025, and December 31, 2025,...

  #4 [page 1, ChunkType.TABLE, 1722 tok] dense=0.441 bm25=3.6
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-ba...

  #5 [page 1, ChunkType.TABLE, 176 tok] dense=0.408 bm25=3.6
  |GAAP operating income range<br>Stock-based compensation<br>Amortization of acquired intangible assets<br>Acquisition related expense<br>Restructuring charges<br>Non-GAAP operating income range|**Thre...

================================================================================
pymupdf4llm + structure_aware — MISS (top-5, hybrid)
================================================================================

  #1 [page 1, ChunkType.TEXT, 294 tok] dense=0.544 bm25=9.1
  [**Additional Recent Business Highlights**]  - Grew Customers to 288,706 at December 31, 2025, up 16% from December 31, 2024. Average Subscription Revenue Per Customer was $11,683 during the fourth qu...

  #2 [page 1, ChunkType.TEXT, 340 tok] dense=0.535 bm25=7.1
  [**Non-GAAP Financial Measures**]  > **(1)** Non-GAAP net income was $95.9 million, $117.3 million, $140.3 million, and $162.5 million for the three months ended March 31, 2025, June 30, 2025, Septemb...

  #3 [page 1, ChunkType.TEXT, 170 tok] dense=0.611 bm25=5.3
  [**Business Outlook**]  Based on information available as of February 11, 2026, HubSpot is issuing guidance for the first quarter and full year of 2026 as indicated below.   **First Quarter 2026:**   ...

  #4 [page 1, ChunkType.TEXT, 189 tok] dense=0.450 bm25=6.9
  [**Conference Call Information**]  HubSpot will host a conference call on Wednesday, February 11, 2026 at 4:30 p.m. Eastern Time (ET) to discuss the company’s fourth quarter and full year 2025 financi...

  #5 [page 1, ChunkType.CHART_DESCRIPTION, 989 tok] dense=0.451 bm25=5.8
  [**Non-GAAP Financial Measures**] We report our financial results in accordance with accounting principles generally accepted in the United States of America, or GAAP. However, management believes tha...

================================================================================
pymupdf4llm + table_aware — MISS (top-5, hybrid)
================================================================================

  #1 [page 1, ChunkType.TEXT, 472 tok] dense=0.601 bm25=8.4
  ## **Balance Sheet and Cash Flow**  - The company’s cash and cash equivalents, short-term, and long-term investments balance was $1.8 billion as of December 31, 2025. - During the fourth quarter, the ...

  #2 [page 1, ChunkType.TEXT, 507 tok] dense=0.595 bm25=7.7
  **==> picture [75 x 21] intentionally omitted <==** ## **HubSpot Reports Strong Q4 and Full Year 2025 Results**  February 11, 2026  _Q4'25 revenue grew 20% on an as-reported basis and 18% in constant ...

  #3 [page 1, ChunkType.TEXT, 331 tok] dense=0.559 bm25=6.8
  > **(1)** Non-GAAP net income was $95.9 million, $117.3 million, $140.3 million, and $162.5 million for the three months ended March 31, 2025, June 30, 2025, September 30, 2025, and December 31, 2025,...

  #4 [page 1, ChunkType.TEXT, 478 tok] dense=0.618 bm25=4.3
  Heading into 2026, we're cementing our position as the leading agentic customer platform for scaling companies, building on our strength upmarket, and leading the new era of marketing with products an...

  #5 [page 1, ChunkType.TEXT, 480 tok] dense=0.507 bm25=6.8
  Expense for the amortization of acquired intangible assets is excluded from non-GAAP expense and income measures as HubSpot views amortization of these assets as arising from pre-acquisition activitie...

================================================================================
pymupdf4llm + heading_based — MISS (top-5, hybrid)
================================================================================

  #1 [page 1, ChunkType.TEXT, 294 tok] dense=0.535 bm25=7.4
  ## **Additional Recent Business Highlights**   - Grew Customers to 288,706 at December 31, 2025, up 16% from December 31, 2024. Average Subscription Revenue Per Customer was $11,683 during the fourth ...

  #2 [page 1, ChunkType.TEXT, 170 tok] dense=0.612 bm25=4.7
  ## **Business Outlook**   Based on information available as of February 11, 2026, HubSpot is issuing guidance for the first quarter and full year of 2026 as indicated below.   **First Quarter 2026:** ...

  #3 [page 1, ChunkType.TABLE, 556 tok] dense=0.563 bm25=4.5
  |Non-GAAP net income(1)<br>Non-GAAP net income per share:<br>Basic(2)<br>Diluted(3)||**Three months ended**|**Three months ended**|**December 31,**<br>**2025**<br>$ 172,682<br>$ 3.29<br>$ 3.29|**Year ...

  #4 [page 1, ChunkType.TEXT, 189 tok] dense=0.445 bm25=6.7
  ## **Conference Call Information**   HubSpot will host a conference call on Wednesday, February 11, 2026 at 4:30 p.m. Eastern Time (ET) to discuss the company’s fourth quarter and full year 2025 finan...

  #5 [page 1, ChunkType.CHART_DESCRIPTION, 989 tok] dense=0.446 bm25=5.6
  ## **Non-GAAP Financial Measures**  We report our financial results in accordance with accounting principles generally accepted in the United States of America, or GAAP. However, management believes t...

## 8. Dump all chunks for a chunker + question (both parsers)

In [25]:
# ---- EDIT THIS ----
Q_ID = 'hub_04'
CHUNKER = 'table_aware'
RETRIEVAL = 'hybrid'  # 'dense', 'bm25', or 'hybrid'
# -------------------

q = next(q for q in questions if q['id'] == Q_ID)
q_emb = embedder.embed_query(q['question'])

output = {
    'question_id': q['id'],
    'question': q['question'],
    'expected_keywords': q['expected_keywords'],
    'chunker': CHUNKER,
    'retrieval': RETRIEVAL,
    'parsers': {}
}

for label, cd in [('pymupdf_fast', cd_fast), ('pymupdf4llm', cd_4llm)]:
    data = cd[CHUNKER]
    chunks = data['chunks']
    texts = data['texts']

    dense_scores = cosine_similarity(q_emb, data['embeddings'])
    bm25_scores = data['bm25'].score(q['question'])
    if RETRIEVAL == 'dense': scores = dense_scores
    elif RETRIEVAL == 'bm25': scores = bm25_scores
    else: scores = hybrid_scores(dense_scores, bm25_scores)

    ranked_idx = np.argsort(scores)[::-1]

    chunk_list = []
    for rank, idx in enumerate(ranked_idx):
        has_answer = any(kw.lower() in texts[idx].lower() for kw in q['expected_keywords'])
        chunk_list.append({
            'rank': rank + 1,
            'chunk_index': int(idx),
            'page_num': chunks[idx].metadata.get('page_num', None),
            'chunk_type': str(chunks[idx].metadata.get('chunk_type', '')),
            'tokens': count_tokens(texts[idx]),
            'dense_score': round(float(dense_scores[idx]), 4),
            'bm25_score': round(float(bm25_scores[idx]), 2),
            'hybrid_score': round(float(scores[idx]), 6),
            'has_answer': has_answer,
            'text': texts[idx],
        })

    output['parsers'][label] = {
        'total_chunks': len(chunks),
        'answer_found_in_chunks': [c['chunk_index'] for c in chunk_list if c['has_answer']],
        'chunks': chunk_list,
    }

# Save to JSON
out_path = PROJECT_ROOT / 'experiments' / 'chunking' / 'results' / f'chunks_{DOC}_{CHUNKER}_{Q_ID}.json'
with open(out_path, 'w') as f:
    json.dump(output, f, indent=2)
print(f'Saved all chunks to: {out_path}')

# Print summary
for label in ['pymupdf_fast', 'pymupdf4llm']:
    p = output['parsers'][label]
    answer_in = p['answer_found_in_chunks']
    answer_ranks = [c['rank'] for c in p['chunks'] if c['has_answer']]
    print(f'\n{label}: {p["total_chunks"]} chunks')
    if answer_in:
        print(f'  Answer in chunk(s): {answer_in}, ranked at: {answer_ranks}')
    else:
        print(f'  Answer NOT FOUND in any chunk')

Saved all chunks to: /Users/sarath/work/doc-parser/experiments/chunking/results/chunks_hubspot-q4_table_aware_hub_04.json

pymupdf_fast: 390 chunks
  Answer in chunk(s): [8], ranked at: [4]

pymupdf4llm: 38 chunks
  Answer in chunk(s): [7], ranked at: [19]

## 9. Chonkie TableChunker experiment

Use [Chonkie's TableChunker](https://docs.chonkie.ai/oss/chunkers/table-chunker) to split markdown tables by rows (preserving headers).
Compare against our custom `TableAwareChunker` for retrieval quality.

In [ ]:
try:
    from chonkie import TableChunker
    print('chonkie imported OK')
except ImportError:
    print('Installing chonkie...')
    import subprocess
    subprocess.check_call([sys.executable, '-m', 'pip', 'install', 'chonkie'])
    from chonkie import TableChunker
    print('chonkie installed and imported OK')

In [27]:
import re

def extract_markdown_tables(markdown):
    """Extract pipe-delimited markdown tables from text, returning (table_str, start_line, end_line) tuples."""
    lines = markdown.split('\n')
    tables = []
    table_lines = []
    table_start = None

    for i, line in enumerate(lines):
        if line.strip().startswith('|'):
            if table_start is None:
                table_start = i
            table_lines.append(line)
        else:
            if table_lines:
                tables.append(('\n'.join(table_lines), table_start, i))
                table_lines = []
                table_start = None
    if table_lines:
        tables.append(('\n'.join(table_lines), table_start, len(lines)))

    return tables

def extract_non_table_text(markdown):
    """Extract non-table text segments from markdown."""
    lines = markdown.split('\n')
    segments = []
    current = []

    for line in lines:
        if line.strip().startswith('|'):
            if current:
                text = '\n'.join(current).strip()
                if text:
                    segments.append(text)
                current = []
        else:
            current.append(line)
    if current:
        text = '\n'.join(current).strip()
        if text:
            segments.append(text)

    return segments


# ---- EDIT THIS ----
CHONKIE_CHUNK_SIZE = 512  # max tokens per table chunk
# -------------------

# Use token-based chunking so tables split at a consistent token budget
# regardless of row count
chonkie_chunker = TableChunker(tokenizer='o200k_base', chunk_size=CHONKIE_CHUNK_SIZE)

def chonkie_chunk_markdown(markdown):
    """Chunk markdown: use Chonkie TableChunker for tables, fixed-size for text."""
    tables = extract_markdown_tables(markdown)
    text_segments = extract_non_table_text(markdown)

    all_chunks = []

    # Chunk tables with Chonkie (token-based, headers preserved automatically)
    for table_str, start, end in tables:
        try:
            chunks = chonkie_chunker.chunk(table_str)
            for c in chunks:
                all_chunks.append(Chunk(
                    text=c.text,
                    metadata={'chunk_type': ChunkType.TABLE, 'page_num': 1, 'source': 'chonkie_table'}
                ))
        except Exception as e:
            # Fallback: keep table as single chunk
            all_chunks.append(Chunk(
                text=table_str,
                metadata={'chunk_type': ChunkType.TABLE, 'page_num': 1, 'source': 'chonkie_table_fallback'}
            ))

    # Chunk text segments with fixed-size
    text_chunker = FixedSizeTokenChunker(chunk_size=512, overlap=102)
    full_text = '\n\n'.join(text_segments)
    text_chunks = text_chunker.chunk(full_text)
    for c in text_chunks:
        c.metadata['source'] = 'text_fixed'
    all_chunks.extend(text_chunks)

    return all_chunks


# Build data for both parsers
print(f'Chonkie TableChunker config: tokenizer=o200k_base, chunk_size={CHONKIE_CHUNK_SIZE} tokens\n')

cd_chonkie = {}
for label, md in [('pymupdf_fast', md_fast), ('pymupdf4llm', md_4llm)]:
    chunks = chonkie_chunk_markdown(md)
    texts = [c.text for c in chunks]
    embeddings = embedder.embed_texts(texts)
    bm25 = BM25Index(texts)
    table_count = sum(1 for c in chunks if c.metadata.get('chunk_type') == ChunkType.TABLE)
    cd_chonkie[label] = {'chunks': chunks, 'texts': texts, 'embeddings': embeddings, 'bm25': bm25}
    print(f'{label}: {len(chunks)} chunks (tables: {table_count}), avg {np.mean([count_tokens(t) for t in texts]):.0f} tok')

2026-03-20 07:51:33,862 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,864 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,864 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,864 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,864 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,865 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,865 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,865 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,865 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,865 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,866 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,866 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,866 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,866 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,867 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,867 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,867 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,867 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,868 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,868 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,868 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,868 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,868 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,868 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,869 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,869 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,869 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,869 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,869 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,869 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,869 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,870 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,870 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,870 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,870 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,870 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,870 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,870 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,871 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,871 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,871 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,871 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,871 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,871 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,872 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,872 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,872 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,872 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,872 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,872 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,872 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,872 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,873 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,873 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,873 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,873 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,873 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,873 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,874 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,874 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,874 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,874 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,874 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,874 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,875 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,876 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,876 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,876 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,876 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,876 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,876 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,877 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,877 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,877 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,877 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,878 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,878 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,878 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,879 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,879 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,879 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,879 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,880 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,880 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,880 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,881 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,881 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,881 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,882 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,882 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,883 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,884 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,884 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,884 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,885 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,885 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,885 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,886 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,886 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,887 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,887 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,888 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,888 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,889 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,889 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,890 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,890 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,890 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,891 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,891 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,892 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,892 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,893 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,894 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,894 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,894 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,895 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,895 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,895 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,895 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:33,896 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.

Chonkie TableChunker config: tokenizer=o200k_base, chunk_size=512 tokens

2026-03-20 07:51:35,102 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:35,104 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.
2026-03-20 07:51:35,105 | WARNING  | chonkie.chunker.table:chunk:128 - Table must have at least a header, separator, and one data row. Skipping chunking.

pymupdf_fast: 66 chunks (tables: 28), avg 271 tok
pymupdf4llm: 45 chunks (tables: 31), avg 562 tok

In [28]:
# Compare Chonkie vs our TableAwareChunker on retrieval

TOP_K = 5
RETRIEVAL = 'hybrid'

print(f"{'Q_ID':<10} {'Question':<40} {'fast_ours':>10} {'fast_chonk':>10} {'4llm_ours':>10} {'4llm_chonk':>10}")
print('-' * 120)

totals = {'fast_ours': 0, 'fast_chonkie': 0, '4llm_ours': 0, '4llm_chonkie': 0}

for q in questions:
    q_emb = embedder.embed_query(q['question'])

    # Our table_aware chunker
    fh_ours = get_hit(cd_fast['table_aware'], q_emb, q, TOP_K, RETRIEVAL)
    lh_ours = get_hit(cd_4llm['table_aware'], q_emb, q, TOP_K, RETRIEVAL)

    # Chonkie
    fh_chonkie = get_hit(cd_chonkie['pymupdf_fast'], q_emb, q, TOP_K, RETRIEVAL)
    lh_chonkie = get_hit(cd_chonkie['pymupdf4llm'], q_emb, q, TOP_K, RETRIEVAL)

    totals['fast_ours'] += fh_ours
    totals['fast_chonkie'] += fh_chonkie
    totals['4llm_ours'] += lh_ours
    totals['4llm_chonkie'] += lh_chonkie

    def fmt(hit): return '  HIT' if hit else ' MISS'
    print(f"{q['id']:<10} {q['question'][:38]:<40} {fmt(fh_ours):>10} {fmt(fh_chonkie):>10} {fmt(lh_ours):>10} {fmt(lh_chonkie):>10}")

print('-' * 120)
print(f"{'TOTAL':<10} {'':40} {totals['fast_ours']:>10} {totals['fast_chonkie']:>10} {totals['4llm_ours']:>10} {totals['4llm_chonkie']:>10}")
print(f"\nOurs (table_aware):  fast={totals['fast_ours']}/{len(questions)}, 4llm={totals['4llm_ours']}/{len(questions)}")
print(f"Chonkie TableChunker: fast={totals['fast_chonkie']}/{len(questions)}, 4llm={totals['4llm_chonkie']}/{len(questions)}")

Q_ID       Question                                  fast_ours fast_chonk  4llm_ours 4llm_chonk
------------------------------------------------------------------------------------------------------------------------
hub_01     What was HubSpot's total revenue in Q4          HIT        HIT        HIT        HIT
hub_02     What was HubSpot's non-GAAP operating           HIT        HIT        HIT        HIT
hub_03     How many customers did HubSpot have as          HIT        HIT        HIT        HIT
hub_04     What was HubSpot's total assets as of           HIT        HIT       MISS       MISS
hub_05     What was HubSpot's gross profit in Q4          MISS       MISS       MISS       MISS
hub_06     What was the cash and cash equivalents          HIT        HIT        HIT        HIT
hub_07     What is the expected total revenue for          HIT        HIT        HIT        HIT
hub_08     What was HubSpot's subscription revenu          HIT        HIT        HIT        HIT
hub_09     What was HubSpot's net income per dilu          HIT        HIT        HIT        HIT
hub_10     What was the share repurchase program           HIT        HIT        HIT        HIT
------------------------------------------------------------------------------------------------------------------------
TOTAL                                                        9          9          8          8

Ours (table_aware):  fast=9/10, 4llm=8/10
Chonkie TableChunker: fast=9/10, 4llm=8/10

In [29]:
# Inspect Chonkie table chunks — see what the chunker produces

# ---- EDIT THIS ----
PARSER = 'pymupdf4llm'  # 'pymupdf_fast' or 'pymupdf4llm'
KEYWORD = '3,854,151'    # keyword to highlight
# -------------------

data = cd_chonkie[PARSER]
chunks = data['chunks']
texts = data['texts']

table_chunks = [(i, c, t) for i, (c, t) in enumerate(zip(chunks, texts))
                if c.metadata.get('chunk_type') == ChunkType.TABLE]

print(f'{PARSER} — Chonkie table chunks: {len(table_chunks)} / {len(chunks)} total\n')

for i, chunk, text in table_chunks:
    tok = count_tokens(text)
    src = chunk.metadata.get('source', '?')
    has_kw = KEYWORD.lower() in text.lower() if KEYWORD else False
    marker = ' << KEYWORD' if has_kw else ''
    preview = text[:300].replace('\n', ' ')
    print(f'  Chunk {i} [{src}, {tok} tok]{marker}')
    print(f'  {preview}...\n')

pymupdf4llm — Chonkie table chunks: 31 / 45 total

  Chunk 0 [chonkie_table, 589 tok] << KEYWORD
  |Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development cos...

  Chunk 1 [chonkie_table, 525 tok] << KEYWORD
  |Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development cos...

  Chunk 2 [chonkie_table, 571 tok] << KEYWORD
  |Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development cos...

  Chunk 3 [chonkie_table, 549 tok] << KEYWORD
  |Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development cos...

  Chunk 4 [chonkie_table, 566 tok] << KEYWORD
  |Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development cos...

  Chunk 5 [chonkie_table, 525 tok] << KEYWORD
  |Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development cos...

  Chunk 6 [chonkie_table, 523 tok] << KEYWORD
  |Current assets:<br>Cash and cash equivalents<br> <br>Short-term investments<br>Accounts receivable<br>Deferred commission expense<br>Prepaid expenses and other current assets<br> <br>Total current assets<br>Long-term investments<br>Property and equipment, net<br>Capitalized software development cos...

  Chunk 7 [chonkie_table, 436 tok]
  |Revenues:<br>Subscription<br>Professional services and other<br>Total revenue<br>Cost of revenues:<br>Subscription<br>Professional services and other<br>Total cost of revenues<br>Gross profit<br>Operating expenses:<br>Research and development<br>Sales and marketing<br>General and administrative<br>...

  Chunk 8 [chonkie_table, 498 tok]
  |Revenues:<br>Subscription<br>Professional services and other<br>Total revenue<br>Cost of revenues:<br>Subscription<br>Professional services and other<br>Total cost of revenues<br>Gross profit<br>Operating expenses:<br>Research and development<br>Sales and marketing<br>General and administrative<br>...

  Chunk 9 [chonkie_table, 407 tok]
  |Revenues:<br>Subscription<br>Professional services and other<br>Total revenue<br>Cost of revenues:<br>Subscription<br>Professional services and other<br>Total cost of revenues<br>Gross profit<br>Operating expenses:<br>Research and development<br>Sales and marketing<br>General and administrative<br>...

  Chunk 10 [chonkie_table, 365 tok]
  |Other income (expense)<br>Total other income<br>Income before income tax expense<br>Income tax expense<br>Net income<br>Net income per share, basic<br>Net income per share, diluted<br>Weighted average common shares used in computing basic net<br>income per share:<br>Weighted average common shares u...

  Chunk 11 [chonkie_table, 1152 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 12 [chonkie_table, 1319 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 13 [chonkie_table, 908 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 14 [chonkie_table, 972 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 15 [chonkie_table, 909 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 16 [chonkie_table, 922 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 17 [chonkie_table, 908 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 18 [chonkie_table, 909 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 19 [chonkie_table, 916 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 20 [chonkie_table, 907 tok]
  |**Operating Activities:**<br>Net income<br>Adjustments to reconcile net (loss) income to net cash and cash<br>equivalents provided by operating activities<br>Depreciation and amortization<br>Stock-based compensation<br>Gain on strategic investments<br>Impairment of strategic investments<br>Provisio...

  Chunk 21 [chonkie_table, 564 tok]
  |GAAP operating income (loss)<br>Stock-based compensation<br>Amortization of acquired intangible assets<br>Acquisition related expense<br>Restructuring charges<br>Non-GAAP operating income<br>GAAP operating margin<br>Non-GAAP operating margin|**Three Months Ended December**<br>**31,**<br>**2025**<br...

  Chunk 22 [chonkie_table, 469 tok]
  |GAAP operating income (loss)<br>Stock-based compensation<br>Amortization of acquired intangible assets<br>Acquisition related expense<br>Restructuring charges<br>Non-GAAP operating income<br>GAAP operating margin<br>Non-GAAP operating margin|**Three Months Ended December**<br>**31,**<br>**2025**<br...

  Chunk 23 [chonkie_table, 574 tok]
  |GAAP net income<br>Stock-based compensation<br>Acquisition related expense<br>Amortization of acquired intangibles assets<br>Restructuring charges<br>Non-cash interest expense for amortization of debt issuance costs<br>(Gain on) impairment of strategic investments, net<br>Income tax effects of non-...

  Chunk 24 [chonkie_table, 137 tok]
  |GAAP expense<br>Stock -based<br>compensation<br>Amortization of<br>acquired intangible<br>assets<br>Acquisition related<br>expense<br>Non-GAAP expense <br>GAAP expense as a<br>percentage of<br>revenue<br>Non-GAAP expense<br>as a percentage of<br>revenue||||**Three**|**Months Ended December 31,**|**...

  Chunk 25 [chonkie_table, 487 tok]
  |||||||**Year Ended December**|**Year Ended December**|**Year Ended December**|**31,**|||||| |---|---|---|---|---|---|---|---|---|---|---|---|---|---|---| |||||**2025**||||||||**2024**||| ||||**COS,**||||||||**COS,**|||| ||**COS,**||**Prof.**|||||**COS,**|||**Prof.**|||| ||**Subs-**|**services**||||...

  Chunk 26 [chonkie_table, 211 tok]
  |||||||**Year Ended December**|**Year Ended December**|**Year Ended December**|**31,**|||||| |---|---|---|---|---|---|---|---|---|---|---|---|---|---|---| |revenue|14.2%||2.0%|28.9%|<br>44.1%||10.4%|<br>12.8%|||2.1%|29.6%|<br>46.4%|11.4%| |Non-GAAP||||||||||||||| |expense as a||||||||||||||| |percen...

  Chunk 27 [chonkie_table, 341 tok]
  |GAAP net cash and cash equivalents provided by operating<br>activities<br> <br>Purchases of property and equipment<br>Capitalization of software development costs<br>Payment of restructuring charges<br> <br>Non-GAAP free cash flow<br> <br>**Supplemental disclosures:**<br>Holdback payments to key em...

  Chunk 28 [chonkie_table, 158 tok]
  |GAAP net cash and cash equivalents provided by operating<br>activities<br> <br>Payment of restructuring charges<br>|**Three Months Ended December**<br>**31,**<br>**2025**<br>**2024**<br>$ 247,430 $ 194,141<br> <br>5,710<br>4,490|**Year Ended December 31,**|**Year Ended December 31,**| |---|---|---|...

  Chunk 29 [chonkie_table, 91 tok]
  |Non-GAAP operating cash flow<br> <br>**Supplemental disclosures:**<br>Holdback payments to key employees related to acquisitions(1)<br>|$ 253,140<br>$ 14,194|$ 198,631<br>$ 2,056|$ 778,705|$ 615,626| |---|---|---|---|---| ||||$ 14,963|$ 2,262|...

  Chunk 30 [chonkie_table, 228 tok]
  |Non-GAAP net income(1)<br>Non-GAAP net income per share:<br>Basic(2)<br>Diluted(3)||**Three months ended**|**Three months ended**|**December 31,**<br>**2025**<br>$ 172,682<br>$ 3.29<br>$ 3.29|**Year ended**| |---|---|---|---|---|---| ||**March 31,**<br>**2025**<br>$ 101,901<br>$ 1.95<br>$ 1.89|**Ju...

In [31]:
# Deep-dive: Chonkie retrieval for a specific question

# ---- EDIT THIS ----
Q_ID = 'hub_04'
TOP_K = 10
RETRIEVAL = 'hybrid'
# -------------------

q = next(q for q in questions if q['id'] == Q_ID)
q_emb = embedder.embed_query(q['question'])

for label in ['pymupdf_fast', 'pymupdf4llm']:
    data = cd_chonkie[label]
    chunks = data['chunks']
    texts = data['texts']

    dense_scores = cosine_similarity(q_emb, data['embeddings'])
    bm25_scores = data['bm25'].score(q['question'])
    scores = hybrid_scores(dense_scores, bm25_scores)

    top_idx = np.argsort(scores)[::-1][:TOP_K]
    top_text = ' '.join(texts[i] for i in top_idx)
    hit = any(kw.lower() in top_text.lower() for kw in q['expected_keywords'])

    # Find which chunk has the answer
    answer_chunks = [i for i, t in enumerate(texts)
                     if any(kw.lower() in t.lower() for kw in q['expected_keywords'])]
    answer_ranks = [np.where(np.argsort(scores)[::-1] == i)[0][0] + 1 for i in answer_chunks]

    print(f"\n{'='*80}")
    print(f"Chonkie + {label} — {'HIT' if hit else 'MISS'} (top-{TOP_K}, {RETRIEVAL})")
    print(f"Q: {q['question']}")
    print(f"Expected: {q['expected_keywords']}")
    if answer_chunks:
        print(f"Answer in chunk(s) {answer_chunks}, ranked at {answer_ranks}")
    else:
        print("Answer NOT FOUND in any chunk")
    print(f"{'='*80}")

    for rank, idx in enumerate(top_idx):
        ctype = chunks[idx].metadata.get('chunk_type', '?')
        src = chunks[idx].metadata.get('source', '?')
        tok = count_tokens(texts[idx])
        has_answer = any(kw.lower() in texts[idx].lower() for kw in q['expected_keywords'])
        marker = ' << ANSWER' if has_answer else ''
        preview = texts[idx].replace('\n', ' ')
        print(f"\n  #{rank+1} [{ctype}, {src}, {tok} tok] dense={dense_scores[idx]:.3f} bm25={bm25_scores[idx]:.1f}{marker}")
        print(f"  {preview}...")

================================================================================
Chonkie + pymupdf_fast — HIT (top-10, hybrid)
Q: What was HubSpot's total assets as of December 31, 2025?
Expected: ['3,854,151']
Answer in chunk(s) [36, 37], ranked at [np.int64(5), np.int64(7)]
================================================================================

  #1 [ChunkType.MIXED, text_fixed, 493 tok] dense=0.601 bm25=8.4
  HubSpot Reports Strong Q4 and Full Year 2025 Results February 11, 2026 Q4'25 revenue grew 20% on an as-reported basis and 18% in constant currency compared to Q4'24 Full year 2025 revenue grew 19% on an as-reported basis and 18% in constant currency compared to 2024 CAMBRIDGE, Mass.--(BUSINESS WIRE)--Feb. 11, 2026-- HubSpot, Inc. (NYSE: HUBS), the customer platform for scaling companies, today announced financial results for the fourth quarter and full year ended December 31, 2025. Financial Highlights: Revenue Fourth Quarter 2025: Total revenue was $846.7 million, up 20% on an as-reported basis and 18% in constant currency compared to Q4'24. Subscription revenue was $829.0 million, up 21% on an as-reported basis compared to Q4'24. Professional services and other revenue was $17.8 million, up 12% on an as-reported basis compared to Q4'24. Full Year 2025: Total revenue was $3.13 billion, up 19% on an as-reported basis and 18% in constant currency compared to 2024. Subscription revenue was $3.06 billion, up 19% on an as-reported basis compared to 2024. Professional services and other revenue was $67.3 million, up 16% on an as-reported basis compared to 2024. Operating Income (Loss) Fourth Quarter 2025: GAAP operating margin was 5.7%, compared to (1.5%) in Q4'24. Non-GAAP operating margin was 22.6%, compared to 18.9% in Q4'24. GAAP operating income was $48.2 million, compared to operating loss of ($10.8) million in Q4'24. Non-GAAP operating income was $191.0 million, compared to $133.1 million in Q4'24. Full Year 2025: GAAP operating margin was 0.2%, compared to (2.6%) in 2024. Non-GAAP operating margin was 18.6%, compared to 17.5% in 2024....

  #2 [ChunkType.MIXED, text_fixed, 472 tok] dense=0.640 bm25=7.7
  During 2025, the company generated $760.7 million of cash from operating cash flow, compared to $598.6 million during 2024. During 2025, the company generated $778.7 million of cash from non-GAAP operating cash flow and $594.9 million of non-GAAP free cash flow, compared to $615.6 million of cash from non-GAAP operating cash flow and $488.1 million of non-GAAP free cash flow during 2024. Additional Recent Business Highlights Grew Customers to 288,706 at December 31, 2025, up 16% from December 31, 2024. Average Subscription Revenue Per Customer was $11,683 during the fourth quarter of 2025, up 3% on an as-reported basis compared to the fourth quarter of 2024. Calculated billings were $971.4 million in the fourth quarter of 2025, up 27% on an as-reported basis and 20% in constant currency compared to Q4'24. “2025 was a transformative year for HubSpot, defined by the momentum of our agentic customer platform and clear acceleration upmarket,” said Yamini Rangan, Chief Executive Officer at HubSpot. “AI adoption gathered pace, as Breeze Customer Agent and Breeze Prospecting Agent delivered real outcomes for customers. At the same time, our upmarket business saw strong momentum, as large companies turned to HubSpot to drive AI innovation, consolidate tech stacks, and reduce their total cost of ownership. Heading into 2026, we're cementing our position as the leading agentic customer platform for scaling companies, building on our strength upmarket, and leading the new era of marketing with products and a playbook that drive growth. We're entering the year with focus and urgency, and I'm confident we're positioned to drive durable growth in the years ahead.” Share Repurchase Program On February 7, 2026, the company’s Board of Directors authorized a share repurchase program for the repurchase of shares of the company’s common stock, in an aggregate amount of up to $1.0 billion (the “2026 Share Repurchase Program”) over a period of up to 24 months....

  #3 [ChunkType.MIXED, text_fixed, 320 tok] dense=0.575 bm25=7.4
  (1) Non-GAAP net income was $95.9 million, $117.3 million, $140.3 million, and $162.5 million for the three months ended March 31, 2025, June 30, 2025, September 30, 2025, and December 31, 2025, respectively, and $516.0 million for the year ended December 31, 2025. (2) Non-GAAP basic net income per share was $1.84, $2.23, $2.67, and $3.10 for the three months ended March 31, 2025, June 30, 2025, September 30, 2025, and December 31, 2025, respectively, and $9.84 for the year ended December 31, 2025. (3) Non-GAAP diluted net income per share was $1.78, $2.19, $2.66, and $3.09 for the three months ended March 31, 2025, June 30, 2025, September 30, 2025, and December 31, 2025, respectively, and $9.70 for the year ended December 31, 2025. View source version on businesswire.com: https://www.businesswire.com/news/home/20260211469584/en/ Investor Relations Contact: investors@hubspot.com Media Contact: media@hubspot.com Source: HubSpot, Inc....

  #4 [ChunkType.MIXED, text_fixed, 496 tok] dense=0.581 bm25=5.5
  First Quarter 2026: Total revenue is expected to be in the range of $862.0 million to $863.0 million, up 21% year over year on an as-reported basis and 16% in constant currency. Non-GAAP operating income is expected to be in the range of $144.0 million to $145.0 million, representing a 17% operating profit margin. Non-GAAP net income per common share is expected to be in the range of $2.46 to $2.48. This assumes approximately 52.5 million weighted average diluted shares outstanding. Full Year 2026: Total revenue is expected to be in the range of $3.69 billion to $3.70 billion, up 18% year over year on an as-reported basis and 16% in constant currency. Non-GAAP operating income is expected to be in the range of $736.0 million to $740.0 million, representing a 20% operating profit margin. Non-GAAP net income per common share is expected to be in the range of $12.38 to $12.46. This assumes approximately 51.8 million weighted average diluted shares outstanding. Use of Non-GAAP Financial Measures In our earnings press releases, conference calls, slide presentations, and webcasts, we may use or discuss non-GAAP financial measures, as defined by Regulation G. The GAAP financial measure most directly comparable to each non-GAAP financial measure used or discussed, and a reconciliation of the differences between each non-GAAP financial measure and the comparable GAAP financial measure, are included in this press release after the consolidated financial statements. Our earnings press releases containing such non-GAAP reconciliations can be found in the Investors section of our website ir.hubspot.com. Conference Call Information HubSpot will host a conference call on Wednesday, February 11, 2026 at 4:30 p.m. Eastern Time (ET) to discuss the company’s fourth quarter and full year 2025 financial results and its business outlook. To register for this conference call, please use this dial in registration link or visit HubSpot's Investor Relations website at ir.hubspot.com. After registering, a confirmation email will be sent, including dial-in details and a unique code for entry. Participants who wish to register for the conference call webcast please use this link....

  #5 [ChunkType.MIXED, text_fixed, 512 tok] dense=0.443 bm25=6.8 << ANSWER
  Current assets:          Cash and cash equivalents  $ 882,242  $ 512,667  Short-term investments    821,552    1,556,828  Accounts receivable    419,146    334,829  Deferred commission expense    226,184    148,693  Prepaid expenses and other current assets    100,611    80,586  Total current assets    2,449,735    2,633,603  Long-term investments    136,662    154,212  Property and equipment, net    141,869    114,165  Capitalized software development costs, net    213,794    154,484  Right-of-use assets    200,821    216,230  Deferred commission expense, net of current portion    218,991    160,814  Other assets    165,602    115,254  Intangible assets, net    35,225    37,563  Goodwill    291,452    209,508  Total assets    3,854,151    3,795,833  Liabilities and stockholders’ equity          Current liabilities:          Accounts payable    24,764    3,649  Accrued compensation costs    99,195    67,442  Accrued commissions    132,003    102,043  Accrued expenses and other current liabilities    166,861    125,135  Operating lease liabilities    39,703    32,693  Convertible senior notes   —    458,184  Deferred revenue    1,004,945    784,253  Total current liabilities    1,467,471    1,573,399  Operating lease liabilities, net of current portion    222,602    254,539  Deferred revenue, net of current portion    8,495    3,969  Other long-term liabilities    89,339    55,640  Total liabilities    1,787,907    1,887,547  Stockholders’ equity:          Common stock    53    52  Treasury stock    2    —  Additional paid-in capital    2,814,843    2,713,697  Accumulated other comprehensive income (loss)    5,244    (5,654) Accumulated deficit    (753,898)    (799,809) Total stockholders’ equity    2,066,244    1,908,286  Total liabilities and stockholders’ equity  $ 3,854,151  $ 3,795,833 ...

  #6 [ChunkType.MIXED, text_fixed, 474 tok] dense=0.444 bm25=6.5
  52.5 million, compared to 51.7 million basic and 52.2 million diluted shares in Q4'24. Weighted average basic and diluted shares outstanding for non-GAAP net income per share was 52.5 million, compared to 51.7 million and 53.9 million, respectively in Q4'24. Full Year 2025: GAAP net income was $45.9 million, or $0.88 per basic and $0.86 per diluted share, compared to $4.6 million, or $0.09 per basic and diluted share in 2024. Non-GAAP net income was $516.0 million, or $9.84 per basic and $9.70 per diluted share, compared to $434.1 million, or $8.48 per basic and $8.12 per diluted share in 2024. Weighted average basic and diluted shares outstanding for GAAP net income per share was 52.5 million and 53.2 million, respectively, compared to 51.2 million basic and 51.8 million diluted shares in 2024. Weighted average basic and diluted shares outstanding for non-GAAP net income per share was 52.5 million and 53.2 million, respectively, compared to 51.2 million and 53.4 million, respectively in 2024. Balance Sheet and Cash Flow The company’s cash and cash equivalents, short-term, and long-term investments balance was $1.8 billion as of December 31, 2025. During the fourth quarter, the company generated $247.4 million of cash from operating cash flow, compared to $194.1 million during Q4'24. During the fourth quarter, the company generated $253.1 million of cash from non-GAAP operating cash flow and $209.4 million of non-GAAP free cash flow, compared to $198.6 million of cash from non-GAAP operating cash flow and $163.0 million of non-GAAP free cash flow during Q4'24. During 2025, the company generated $760.7 million of cash from operating cash flow, compared to $598.6 million during 2024....

  #7 [ChunkType.MIXED, text_fixed, 509 tok] dense=0.425 bm25=6.8 << ANSWER
  Accumulated deficit    (753,898)    (799,809) Total stockholders’ equity    2,066,244    1,908,286  Total liabilities and stockholders’ equity  $ 3,854,151  $ 3,795,833  Consolidated Statements of Operations (in thousands, except per share data)     Three Months Ended December 31,    Year Ended December 31,     2025    2024    2025    2024   Revenues:                Subscription $ 828,980  $ 687,316  $ 3,063,917  $ 2,569,546  Professional services and other   17,766    15,856    67,349    57,997  Total revenue   846,746    703,172    3,131,266    2,627,543  Cost of revenues:                Subscription   121,411    89,505    445,336    336,878  Professional services and other   16,290    13,867    63,151    56,387  Total cost of revenues   137,701    103,372    508,487    393,265  Gross profit   709,045    599,800    2,622,779    2,234,278  Operating expenses:                Research and development   220,794    213,711    905,943    778,714  Sales and marketing   357,531    314,864    1,379,376    1,218,844  General and administrative   81,668    80,931    326,045    300,332  Restructuring   814    1,143    4,036    3,990  Total operating expenses   660,807    610,649    2,615,400    2,301,880  Income (loss) from operations   48,238    (10,849)    7,379    (67,602) Other income (expense)                Interest income   13,112    21,829    66,218    82,706  Interest expense —    (949)    (876)    (3,721) ### Tables , | 512667 , | , | 1556828 , , | , | 334829 , | , | 148693 , | , | 80586 , | , , | 2633603 , , |...

  #8 [ChunkType.MIXED, text_fixed, 511 tok] dense=0.534 bm25=4.8
  Eastern Time (ET) to discuss the company’s fourth quarter and full year 2025 financial results and its business outlook. To register for this conference call, please use this dial in registration link or visit HubSpot's Investor Relations website at ir.hubspot.com. After registering, a confirmation email will be sent, including dial-in details and a unique code for entry. Participants who wish to register for the conference call webcast please use this link. An archived webcast of this conference call will also be available on HubSpot's Investor Relations website at ir.hubspot.com. The company has used, and intends to continue to use, the investor relations portion of its website as a means of disclosing material non-public information and for complying with disclosure obligations under Regulation FD. About HubSpot HubSpot is the agentic customer platform that helps businesses connect and grow better. HubSpot delivers seamless connection for customer-facing teams with a unified platform that includes AI-powered engagement hubs, a Smart CRM, and a connected ecosystem with over 2,000 App Marketplace integrations, a community network, and educational content. Learn more at www.hubspot.com. Cautionary Language Concerning Forward-Looking Statements This press release includes certain “forward-looking statements” within the meaning of the Private Securities Litigation Reform Act of 1995, including statements regarding management’s expectations of future financial and operational performance and operational expenditures, expected growth, foreign currency movement, and business outlook, including our financial guidance for the first fiscal quarter of and full year 2026 and our long-term financial framework; statements regarding our share repurchase program; statements regarding our positioning for future growth and market leadership; statements regarding the strength of our agentic customer platform; statements regarding the growth or maintenance of our upmarket business; statements regarding the economic environment; and statements regarding expected market trends, future priorities and related investments, and market opportunities. These forward-looking statements include, but are not limited to, plans, objectives, expectations and intentions and other statements contained in this press release that are not historical facts and statements identified by words such as “expects,” “anticipates,” “intends,” “plans,” “believes,” “seeks,” “estimates” or words of similar meaning. These forward-looking statements reflect our current views about our plans, intentions, expectations, strategies and prospects, which are based on the information currently available to us and on assumptions we have made....

  #9 [ChunkType.MIXED, text_fixed, 369 tok] dense=0.523 bm25=4.8
  These forward-looking statements reflect our current views about our plans, intentions, expectations, strategies and prospects, which are based on the information currently available to us and on assumptions we have made. Although we believe that our plans, intentions, expectations, strategies and prospects as reflected in or suggested by those forward-looking statements are reasonable, we can give no assurance that the plans, intentions, expectations or strategies will be attained or achieved. Furthermore, actual results may differ materially from those described in the forward-looking statements and will be affected by a variety of risks and factors that are beyond our control including, without limitation, risks associated with our history of losses; our ability to retain existing customers and add new customers; the continued growth of the market for a customer platform; our ability to develop new products and technologies and differentiate our platform from competing products and technologies, including artificial intelligence and machine learning technologies; our ability to manage our growth effectively over the long-term to maintain our high level of service; our ability to maintain and expand relationships with our solutions partners; the price volatility of our common stock; the impact of geopolitical conflicts, inflation, foreign currency movement, and macroeconomic instability on our business, the broader economy, our workforce and operations, the markets in which we and our partners and customers operate, and our ability to forecast our future financial performance; regulatory and legislative developments on the use of artificial intelligence and machine learning; and other risks set forth under the caption “Risk Factors” in our SEC filings. We assume no obligation to update any forward-looking statements contained in this document as a result of new information, future events or otherwise. Consolidated Balance Sheets (in thousands)       December 31,    December 31,       2025    2024   Assets          ---...

  #10 [ChunkType.MIXED, text_fixed, 506 tok] dense=0.539 bm25=4.4
  Restructuring charges   1,011    4,044  Non-GAAP operating income range $144,000-$145,000    $736,000-$740,000   Reconciliation of forecasted non-GAAP net income and non-GAAP net income per share (in thousands, except per share amounts) Three Months Ended March 31, 2026    Year Ended December 31, 2026   GAAP net income range $34,017-$35,194    $138,271-$142,977   Stock-based compensation   108,731    556,772  Amortization of acquired intangible assets   3,192    12,411  Acquisition related expense   4,931    15,561  Restructuring charges   1,011    4,044  Income tax effects of non-GAAP items (22,782)-(22,959)    (85,259)-(85,965)   Non-GAAP net income range $129,100-$130,100    $641,800-$645,800            GAAP net income per basic and diluted share $0.65-$0.67    $2.67-$2.76   Non-GAAP net income per diluted share $2.46-$2.48    $12.38-$12.46                     Weighted average common shares used in computing GAAP basic net income per share:   52,419    51,791  Weighted average common shares used in computing GAAP and non-GAAP diluted net income per share:   52,492    51,842  HubSpot’s estimates of stock-based compensation, amortization of acquired intangible assets, interest expense for amortization of one-time upfront debt issuance costs, restructuring charges, and income tax effects of non-GAAP items assume, among other things, the occurrence of no additional acquisitions, changes in value of strategic investments, and no further revisions to stock-based compensation and related expenses. Non-GAAP Financial Measures We report our financial results in accordance with accounting principles generally accepted in the United States of America, or GAAP. However, management believes that, in order to properly understand our short-term and long-term financial and operational trends, investors may wish to consider the impact of certain non-cash or non-recurring items when used as a supplement to financial performance measures in accordance with GAAP....

================================================================================
Chonkie + pymupdf4llm — MISS (top-10, hybrid)
Q: What was HubSpot's total assets as of December 31, 2025?
Expected: ['3,854,151']

In [ ]:
# Sweep Chonkie chunk_size (tokens) to find optimal table chunk size

TOP_K = 5
RETRIEVAL = 'hybrid'
TOKEN_SIZES = [128, 256, 512, 768, 1024]

print(f"Sweeping Chonkie TableChunker token sizes: {TOKEN_SIZES}")
print(f"{'tok_size':>8} {'parser':<15} {'chunks':>7} {'tables':>7} {'avg_tok':>8} {'hits':>5} {'total':>6}")
print('-' * 65)

for tok_size in TOKEN_SIZES:
    tc = TableChunker(tokenizer='o200k_base', chunk_size=tok_size)

    for label, md in [('pymupdf_fast', md_fast), ('pymupdf4llm', md_4llm)]:
        tables = extract_markdown_tables(md)
        text_segments = extract_non_table_text(md)
        all_chunks = []

        for table_str, start, end in tables:
            try:
                chunks = tc.chunk(table_str)
                for c in chunks:
                    all_chunks.append(Chunk(
                        text=c.text,
                        metadata={'chunk_type': ChunkType.TABLE, 'page_num': 1}
                    ))
            except:
                all_chunks.append(Chunk(
                    text=table_str,
                    metadata={'chunk_type': ChunkType.TABLE, 'page_num': 1}
                ))

        text_chunker = FixedSizeTokenChunker(chunk_size=512, overlap=102)
        full_text = '\n\n'.join(text_segments)
        all_chunks.extend(text_chunker.chunk(full_text))

        texts = [c.text for c in all_chunks]
        embeddings = embedder.embed_texts(texts)
        bm25 = BM25Index(texts)
        data = {'chunks': all_chunks, 'texts': texts, 'embeddings': embeddings, 'bm25': bm25}

        table_count = sum(1 for c in all_chunks if c.metadata.get('chunk_type') == ChunkType.TABLE)
        avg_tok = np.mean([count_tokens(t) for t in texts])

        hits = 0
        for q in questions:
            q_emb = embedder.embed_query(q['question'])
            if get_hit(data, q_emb, q, TOP_K, RETRIEVAL):
                hits += 1

        print(f"{tok_size:>8} {label:<15} {len(all_chunks):>7} {table_count:>7} {avg_tok:>8.0f} {hits:>5} {len(questions):>6}")